# Generated by Django 5.2.7 on 2025-11-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital_admin', 'Hospital Admin'), ('staff', 'Staff')], max_length=20),
        ),
    ]
