# Generated by Django 5.2.7 on 2025-11-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.appointment'),
        ),
    ]
